# fly.toml app configuration file generated for gosse on 2024-08-24T21:26:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gosse'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
